### ISSUE TITLE
Running the project from Visual Studio .NET 2022, browser hanging

### ISSUE THREAD

**Issue by reuniware** [OrbitGroup/TriangleCollector#12]
Hello,

When I'm running the project from VS.NET 2022, the browser is started and hangs (loading page infinitely).
It uses IISExpress.

What should I do to run it properly ?

Thanks

**Comment by brasky** [comment]
Hi @reuniware , just a warning before I help you that we are in the midst of developing trading capabilities and so without API keys to Huobi this will not run unless you go back to an older commit. If you are interested in just monitoring profitable triangles on the Huobi exchange I recommend this commit: https://github.com/OrbitGroup/ProjectOrbit/commit/29a3a55a64527f8756593121598f7f63b9aaf2ff


Instead of running the app using IIS, try TriangleCollector (kestrel) 
![image](https://user-images.githubusercontent.com/3758126/146910154-2f84a288-86e1-47f4-80ce-8c72ae53787f.png)

**Comment by reuniware** [comment]
Thank you for your reply.
When I run TriangleCollector, there is no output of what is done by the app...
![image](https://user-images.githubusercontent.com/16271697/146911952-7a211d01-3837-4331-852b-43e71ed6d7b4.png)

I have keys for Huobi API. Where should I enter them ?

Thanks

**Comment by reuniware** [comment]
Are the secret keys retrieved in this function ? 
![image](https://user-images.githubusercontent.com/16271697/146913347-03e78948-6cee-4af9-b49b-e859a5d45b35.png)

**Comment by reuniware** [comment]
Same problem when using the specific commit at https://github.com/OrbitGroup/ProjectOrbit/tree/29a3a55a64527f8756593121598f7f63b9aaf2ff
